[package]
authors     = ["Laocoon <laocoon7@gmail.com>"]
description = "Away Team Roguelike Game"
edition     = "2021"
homepage    = "https://github.com/Laocoon7/atrl"
license     = "BlueOak-1.0.0"
name        = "atrl"
readme      = "README.md"
repository  = "https://github.com/Laocoon7/atrl"
version     = "0.1.0"
#license-file = "LICENSE"
categories = ["games"]
exclude    = ["assets/", "tools/", ".github/", "crates/engine", "crates/utils"]
keywords   = ["game", "ascii", "roguelike"]
resolver   = "2"

######################################
#########    Optimizations    ########
######################################

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

# Optimizations for WASM
[profile.release]
codegen-units = 1
lto           = true
opt-level     = 'z'
panic         = 'abort'

######################################
###########    Workspaces    #########
######################################

[workspace]
members = ["tools/ci", "tools/spancmp", "crates/*"]

[features]
debug   = ["colored"]
default = ["dev"]
dev     = ["atrl-engine/dev"]
release = ["atrl-engine/release"]

[dependencies]
atrl-engine = { path = "crates/engine" }
atrl-utils  = { path = "crates/utils" }

######################################
#########    Serialization    ########
######################################
serde      = { version = "1", features = ["derive"] }
serde_json = "1"

######################################
###########    Utility    ############
######################################

colored       = { version = "2", optional = true }
num-derive    = "0.3"
num-traits    = "0.2"
once_cell     = "1"
parking_lot   = "0.12"
smart-default = { version = "0.6" }
strum         = { version = "0.24", features = ["derive"] }

[dependencies.bevy_asset_loader]
features = ["stageless", "2d", "standard_dynamic_assets"]
git      = "https://github.com/NiklasEi/bevy_asset_loader"

[dependencies.banana_bevy_utils]
features = ["states"]
git      = "https://github.com/banana-studios/banana_bevy_utils"
