[package]
authors     = ["Laocoon <laocoon7@gmail.com>"]
description = "Away Team Roguelike Game"
edition     = "2021"
homepage    = "https://github.com/Laocoon7/atrl"
license     = "BlueOak-1.0.0"
name        = "atrl"
readme      = "README.md"
repository  = "https://github.com/Laocoon7/atrl"
version     = "0.1.0"
#license-file = "LICENSE"
categories = ["games"]
exclude    = ["assets/", "tools/", ".github/"]
keywords   = ["game", "ascii", "roguelike"]
resolver   = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

# Optimizations for WASM
[profile.release]
codegen-units = 1
lto           = true
opt-level     = 'z'
panic         = 'abort'

[workspace]
members = ["tools/ci", "tools/spancmp"]

[features]
default = ["dev"]
dev     = ["bevy/dynamic"]
release = []

[dependencies]
# Serialization
ron        = "0.8"
serde      = { version = "1", features = ["derive"] }
serde_json = "1"

# Random
noise       = "0.8"
rand        = "0.8"
rand_pcg    = { version = "0.3", features = ["serde1"] }
rand_seeder = "0.2"
xxhash-rust = { version = "0.8", features = ["xxh3", "const_xxh3"] }

[dependencies.banana_bevy_utils]
features = ["states"]
git      = "https://github.com/banana-studios/banana_bevy_utils"

# Bevy
[dependencies.bevy]
default-features = false
features         = ["bevy_asset", "bevy_winit", "render", "png", "x11"]
version          = "0.8"

##############
# Bevy Plugins 
##############

[dependencies.iyes_loopless]
features = ["states"]
version  = "0.8"

[dependencies.bevy_ecs_tilemap]
features = ["atlas"]
version  = "0.8"

# Assets
[dependencies.bevy_asset_loader]
features = ["stageless", "2d", "standard_dynamic_assets"]
git      = "https://github.com/NiklasEi/bevy_asset_loader"

[dependencies.bevy_common_assets]
features = ["ron", "toml", "json"]
git      = "https://github.com/NiklasEi/bevy_common_assets"

# Debug + UI
[dependencies.bevy-inspector-egui]
version = "0.13"

#kayak_ui = "0.1.0"
