# Wrap all comments and lines to 80 characters
binop_separator               = "back"
chain_width                   = 100
comment_width                 = 95
edition                       = "2021"
fn_single_line                = true
max_width                     = 100
single_line_if_else_max_width = 100
unstable_features             = true
use_field_init_shorthand      = true
use_small_heuristics          = "Max"
use_try_shorthand             = true
where_single_line             = true
wrap_comments                 = true