[package]
edition = "2021"
name    = "atrl-camera"
version = "0.1.0"

[features]
debug   = []
dev     = []
release = []

[dependencies]
banana_bevy_utils = { workspace = true }
bevy              = { workspace = true }
iyes_loopless     = { workspace = true }
