[package]
name = "atrl-map-gen"
version = "0.1.0"
edition = "2021"

[features]
debug   = []
dev     = []
release = []

[dependencies]
bevy                = {workspace = true}
iyes_loopless       = {workspace = true}
rand                = {workspace = true}

atrl-common         = {workspace = true}